version: '2'
services:
    node:
        build: node/.
        command: node server.js #&& node logScan.js
        #links:
            #    - ror
            #   - redis
        volumes:
            - ./node:/node
            - /node/node_modules
            - /var/log/apache2:/node/apacheLogs
            - ../nginx/logs:/node/nginxLogs
        #ports:
        #    - "8090:8088"
        restart: always
        networks:
           - nginx_default
    http:
        build: http/.
        command: http-server . -p 80
        #depends_on: 
        #    - ror
        #ports:
        #    - "8002:80"
        volumes:
            - ./http/:/http
            - /http/node_modules
        restart: always
        networks:
            - nginx_default
        #redis:
        #image: redis
        #restart: always
networks:
    nginx_default:
        external: true
