version: '2'
services:
    ror:
        build: ror/.
        command: bundle exec rails s -p 3000 -b '0.0.0.0'
        volumes:
            - ./ror:/ror
        ports:
            - "3001:3000"
        restart: always
        networks:
            - nginx_default
    node:
        build: node/.
        command: node server.js
        links:
            - ror
            - redis
        volumes:
            - ./node/server.js:/node/server.js
            - ./node/common.js:/node/common.js
            - ./node/logScan.js:/node/logScan.js
        restart: always
    http:
        build: http/.
        command: http-server . -p 80
        depends_on: 
            - ror
        ports:
            - "8002:80"
        volumes:
            - ./http/js:/http/js
            - ./http/css:/http/css
            - ./http/partials:/http/partials
            - ./http/favicon.ico:/http/favicon.ico
            - ./http/index.html:/http/index.html
        restart: always
        networks:
            - nginx_default
    redis:
        image: redis
        ports:
            - "16379:6379"
        restart: always
networks:
    nginx_default:
        external: true
