version: '2'
services:
    ror:
        build: ror/.
        command: bundle exec rails s -p 3000 -b '0.0.0.0'
        volumes:
            - ./ror:/ror
        ports:
            - "3001:3000"
        restart: always
        networks:
            - nginx_default
    node:
        build: node/.
        command: node server.js
        links:
            - ror
            - redis
        volumes:
            #- ./node/server.js:/node/server.js
            #- ./node/common.js:/node/common.js
            #- ./node/logScan.js:/node/logScan.js
            - ./node/:/node
            - ./node/node_modules:/node/node_modules
            - /var/log/apache2:/node/apacheLogs
            - ../nginx/logs:/node/nginxLogs
        ports:
            - "8090:8088"
        restart: always
    http:
        build: http/.
        command: http-server . -p 80
        depends_on: 
            - ror
        ports:
            - "8002:80"
        volumes:
            - ./http/:/http
            - ./http/node_modules:/http/node_modules
        restart: always
        networks:
            - nginx_default
    redis:
        image: redis
        restart: always
networks:
    nginx_default:
        external: true
